preseed:
  localization:
    language: en
    country: FR
    locale: en_US.UTF-8
    keymap: fr(latin9)
  clock_time_zone:
    timezone: Europe/Paris
  network:
    hostname: customiso
    domain: none
    advanced: 
      ip_config: true
  mirror:
    http_hostname: deb.debian.org
    http_proxy: none
  accounting:
    root:
      enable: true
      password: "$6$o1Ta1wpTDhU.Upde$29fzWrjfStzU3PJnFkKn9zCU3fUrJMBMCBe9Ndcc0j8pPIYe9293msJh8Z.Q2xaD37b6WN4QRKcU9kiKdvoqI0"
    user:
      fullname: Tanguy
      username: tanguy
      password: "$6$M0iPRL3VvFh0JWvr$5kRju/9LFcb6xkdFnmvFCPKh9hHpRyoJG1sOeY4Uaae5pc0onWYiJEHa7QeGjTUE8Y3ULC/vAkZDfdxjhhcfm0"
  partitionning:
    predefined_mode: 1
  packages:
    tasksel:
      - standard
      - ssh-server
    popularity_contest: false
  finishing:
    reboot_message: false
    device_eject: false

additional_packages:
  - /home/tn/Desktop/Customiso/deb_packages/ponysay_3.0.3+20210327-1_all.deb
  - /home/tn/Desktop/Customiso/deb_packages/lsd_0.23.1_amd64.deb

additional_files:
  - from: /home/tn/Desktop/Customiso/Customiso/src/customiso/samples/afile.xml
    to: /etc/config
  - from: /home/tn/Desktop/Customiso/Customiso/src/customiso/samples/somefile.yaml
    to: /var/data
  - from: /home/tn/Desktop/Customiso/Customiso/src/customiso/samples/thefile.json
    to: /bin/program

post_install_script: /home/tn/Desktop/Customiso/Customiso/src/customiso/samples/test_script.sh
